# Change these first
owner: ANPA Mar do Orzan # Your GitHub organization or username, where this repository lives
repo: statusweb # The name of this repository

sites:
  - name: ANPA Mar do Orzan
    url: https://anpamarorzan.com
assignees: # Users to assign downtime issues (optional)
  - rsstudiophotography
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /statusweb
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Pagina de Status de la web del ANPA
  introTitle: "**Upptime** es el monitor de tiempo de actividad de código abierto y la página de estado, impulsado completamente por GitHub."
  introMessage: En esta pagina mos mantenemos informados sobre el status de la pagina de nuestra ANPA
  navbar:
    - title: Status
      href: /
    - title: ANPA
      href: https://anpamarorzan.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
